create table  correct_oil_answer
(
    id          int8 generated by default as identity,
    name_answer varchar(4000),
    primary key (id)
);
create table  correct_oil_answer_correct_answer
(
    correct_oil_answer_id int8 not null,
    correct_answer        varchar(4000)
);
create table  oilall_questions
(
    id     int8 generated by default as identity,
    answer varchar(255),
    name   varchar(4000),
    primary key (id)
);
create table  oil_questions_test_options
(
    oil_questions_id int8 not null,
    test_options     varchar(4000)
);
alter table if exists correct_oil_answer_correct_answer
    add constraint FKhjm0vckk6hactugk101k5d8p foreign key (correct_oil_answer_id) references correct_oil_answer;
alter table if exists oil_questions_test_options
    add constraint FKfoyn2nkvhmfvx4ia84ca3hakx foreign key (oil_questions_id) references oilall_questions;