create table boiler_questions
(
    id     int8 generated by default as identity,
    answer varchar(255),
    name   varchar(4000),
    primary key (id)
);
create table boiler_questions_test_options
(
    boiler_questions_id int8 not null,
    test_options        varchar(4000)
);
create table concrete_boiler_answer_correct_answer
(
    concrete_boiler_answer_id int8 not null,
    correct_answer            varchar(4000)
);
create table correct_boiler_answer
(
    id          int8 generated by default as identity,
    name_answer varchar(4000),
    primary key (id)
);
alter table if exists boiler_questions_test_options
    add constraint FK44upjua6ah3yoa1odd8e7bk24 foreign key (boiler_questions_id) references boiler_questions;
alter table if exists concrete_boiler_answer_correct_answer
    add constraint FK4bt5sc0amkv4fush7jhw4hfdy foreign key (concrete_boiler_answer_id) references correct_boiler_answer;