create table correct_pipe_answer
(
    id             int8 generated by default as identity,
    correct_answer varchar(4000),
    primary key (id)
);
create table pipe_questions
(
    id     int8 generated by default as identity,
    answer varchar(255),
    name   varchar(4000),
    primary key (id)
);
create table pipe_questions_test_options
(
    pipe_questions_id int8 not null,
    test_options      varchar(4000)
);

alter table if exists pipe_questions_test_options
    add constraint FK9o3vl9rstgwqx6cftj7k5syqf foreign key (pipe_questions_id) references pipe_questions;