create table correct_vessel_answer
(
    id             int8 generated by default as identity,
    correct_answer varchar(4000),
    primary key (id)
);
create table vessel_questions
(
    id     int8 generated by default as identity,
    answer varchar(255),
    name   varchar(4000),
    primary key (id)
);
create table vessel_questions_test_options
(
    vessel_questions_id int8 not null,
    test_options        varchar(4000)
);
alter table if exists vessel_questions_test_options
    add constraint FKmytqtmitrkp4lhmb12bivuqqv foreign key (vessel_questions_id) references vessel_questions;